"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import { useRouter, useSearchParams } from "next/navigation";

import { QueryClientProvider, QueryClient } from "@tanstack/react-query";

import { CartProvider } from "../context/cartContext";
import Navbar from "../components/common/Navbar";
import { Toaster } from "react-hot-toast";
import RegisterPage from "./register/page";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "VALLEY STORE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const queryClient = new QueryClient();
  const params = useSearchParams();
  const userExist = params.get("email");

  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <div className="fixed top-0 left-0 z-40 w-full">
            <Navbar />
          </div>
          <QueryClientProvider client={queryClient}>
            {children}
            <Toaster />
          </QueryClientProvider>
        </CartProvider>
      </body>
    </html>
  );
}
